/* BACK OFFICE track content.
   Status tags:  V  = substance verified against the cited rule (as of build knowledge)
                 LV = REQUIRES LIVE VERIFICATION (rule/circular may have been revised or exact cite not confirmed)
                 C  = conduct / control best practice (no single regulatory source)
                 G  = procedurally generated calculation (market convention stated in the question)
   All counterparties, banks and funds are fictional. Market levels are synthetic. */
(function () {
  const D = window.D;
  D.content = D.content || {};
  const F = D.FIRM;

  const S = [
    // ---------- Payments & settlement ----------
    { id: 'bo01', topic: 'Payments', q: 'Which statement on RTGS is correct today?', o: ['24x7x365 since 14-Dec-2020; minimum ₹2 lakh per transaction', '24x7x365 since 14-Dec-2020; no minimum since NEFT went 24x7', '24x7 on working days only; minimum ₹2 lakh per transaction', '24x7x365 for inter-bank only; customer RTGS 07:00–18:00'], a: 0, x: 'RTGS went 24x7x365 from 14-Dec-2020 for both customer and inter-bank transactions. The ₹2 lakh minimum remains — below that, use NEFT (24x7 since 16-Dec-2019).', ref: 'RBI press release 14-Dec-2020 (RTGS 24x7); RTGS System Regulations', s: 'V', d: 1 },
    { id: 'bo02', topic: 'Payments', q: `${F} remits ₹75 Cr via RTGS to a corporate counterparty. Which LEI requirement applies?`, o: ['Remitter LEI mandatory for non-individual remitters on transactions of ₹50 Cr and above', 'Remitter LEI mandatory only on transactions of ₹100 Cr and above', 'LEI mandatory only for cross-border remittances under FEMA', 'LEI optional for NBFCs; mandatory only for banks and PDs'], a: 0, x: 'From 1-Apr-2021, for RTGS and NEFT transactions of ₹50 Cr and above by non-individuals, the remitter LEI must be included (beneficiary LEI information to be included as well). Treasury static data must hold valid, unlapsed LEIs — a lapsed LEI is an operational break.', ref: 'RBI circular dated 05-Jan-2021: LEI for large value transactions in centralised payment systems', s: 'V', d: 2 },
    { id: 'bo03', topic: 'Money markets', q: `${F} (an NBFC-ML) has ₹300 Cr surplus at 11:00. Which deployment is NOT open to it?`, o: ['Lend in the inter-bank call/notice money market', 'Lend overnight in TREPS through CCIL', 'Buy 91-day T-bills in the primary auction', 'Invest in an overnight mutual fund scheme'], a: 0, x: 'Call/notice/term money participation is restricted to banks and standalone primary dealers. NBFCs deploy surplus via TREPS, T-bills, CDs, and liquid/overnight funds.', ref: 'RBI Call, Notice and Term Money Markets Directions — eligible participants [verify current Direction no.]', s: 'V', d: 2 },
    { id: 'bo04', topic: 'Money markets', q: `Which instrument can ${F} NOT issue?`, o: ['Certificate of Deposit (6-month)', 'Commercial Paper (180-day)', 'Short-term NCD (original maturity 1 year)', 'Subordinated Tier II debt (7-year)'], a: 0, x: 'CDs can be issued only by scheduled commercial banks (and select AIFIs). NBFCs raise short-term money through CP and short-term NCDs.', ref: 'RBI Master Direction – Certificate of Deposit (eligible issuers)', s: 'V', d: 1 },
    { id: 'bo05', topic: 'CP operations', q: 'Which CP proposal breaches the RBI CP directions?', o: ['A 5-day CP to fund a long-weekend gap', 'A 7-day CP in ₹5 lakh denomination', 'A 364-day CP issued through a bank IPA', 'A 91-day CP for an issuer rated A1+'], a: 0, x: 'CP tenor: minimum 7 days, maximum 1 year. Weekend gaps below 7 days are funded via TREPS (against G-sec/T-bill collateral) or bank lines.', ref: 'RBI (Commercial Paper and NCDs of original maturity up to one year) Directions, 2024 (03-Jan-2024; effective 01-Apr-2024)', s: 'V', d: 1 },
    { id: 'bo06', topic: 'CP operations', q: 'Minimum denomination of a CP (and multiples thereof):', o: ['₹5 lakh', '₹1 lakh', '₹25 lakh', '₹1 Cr'], a: 0, x: 'CP is issued in minimum denomination of ₹5 lakh and multiples thereof, in dematerialised form.', ref: 'RBI CP & short-term NCD Directions, 2024', s: 'V', d: 1 },
    { id: 'bo07', topic: 'NCD servicing', q: 'An NCD coupon date falls on a Sunday. Per SEBI convention the coupon is paid:', o: ['Next working day; subsequent coupon dates stay as per original schedule', 'Previous working day; subsequent coupon dates stay as per original schedule', 'Next working day; subsequent coupon dates shift by the same number of days', 'Previous working day; final redemption date also shifts to keep the tenor'], a: 0, x: 'Coupon falling on a holiday → paid the next working day; subsequent coupon dates are unchanged. (Redemption falling on a holiday → paid the previous working day.)', ref: 'SEBI circular CIR/IMD/DF-1/122/2016 dt 11-Nov-2016 (now in SEBI Master Circular for NCS)', s: 'V', d: 2 },
    { id: 'bo08', topic: 'NCD servicing', q: 'The final redemption date of a listed NCD falls on a bank holiday. Redemption proceeds are paid:', o: ['On the previous working day', 'On the next working day', 'On the holiday itself, since RTGS is 24x7', 'On the next working day, with interest for the extra day'], a: 0, x: 'SEBI convention: if the maturity date is a holiday, redemption proceeds are paid on the previous working day. Mixing up the coupon rule (next working day) and the redemption rule (previous working day) is a classic ops error.', ref: 'SEBI circular CIR/IMD/DF-1/122/2016 dt 11-Nov-2016', s: 'V', d: 2 },
    { id: 'bo09', topic: 'NCD servicing', q: 'Day count for computing coupon on listed NCDs per SEBI convention:', o: ['Actual/Actual (366-day year when 29-Feb falls in the period)', 'Actual/365 fixed (365 days even in a leap year)', '30/360 (European), as for G-secs', 'Actual/360, as for overseas money markets'], a: 0, x: 'Interest on listed debt securities is computed on Actual/Actual basis; in a leap year the denominator is 366 days.', ref: 'SEBI circular CIR/IMD/DF-1/122/2016 dt 11-Nov-2016', s: 'V', d: 1 },
    { id: 'bo10', topic: 'NCD servicing', q: `${F} pays an NCD redemption 4 days late. Minimum additional interest owed to investors for the delay:`, o: ['At least 2% p.a. over the coupon for the defaulting period', 'At least 1% p.a. over the coupon for the defaulting period', 'At least 2% p.a. over the coupon, only if delay exceeds 7 days', 'Coupon rate only for the delay; penal interest only on listing delays'], a: 0, x: 'Default in payment of interest/redemption attracts additional interest of at least 2% p.a. over the coupon for the defaulting period — plus rating action, exchange disclosure and DT intimation. Operationally, this is the most expensive mistake in BO.', ref: 'SEBI Master Circular for issue and listing of NCS — default interest provisions [verify para]', s: 'V', d: 2 },
    { id: 'bo11', topic: 'NCD servicing', q: `Must ${F} (RBI-registered NBFC) create a Debenture Redemption Reserve on privately placed NCDs?`, o: ['No — RBI-registered NBFCs are exempt for public issues and private placements', 'Yes — 10% of outstanding value for both public issues and private placements', 'Only for public issues (10%); private placements are exempt', 'Only for private placements (25%); public issues are exempt'], a: 0, x: 'The 2019 amendment exempted RBI-registered NBFCs and HFCs from DRR for both public issues and private placements.', ref: 'Companies (Share Capital and Debentures) Amendment Rules, 2019 (notified 16-Aug-2019), Rule 18(7)', s: 'V', d: 2 },
    { id: 'bo12', topic: 'NCD servicing', q: `${F}'s first listed NCD issue is ₹500 Cr. Its Recovery Expense Fund contribution is:`, o: ['₹5 lakh (0.01% of issue size; cap ₹25 lakh per issuer)', '₹25 lakh (the per-issuer cap applies on the first issue)', '₹50 lakh (0.1% of issue size; no cap)', 'Nil — REF applies only to public issues, not private placements'], a: 0, x: '0.01% × ₹500 Cr = ₹5 lakh, deposited with the designated stock exchange; cumulative cap ₹25 lakh per issuer. It funds the debenture trustee\'s enforcement costs on default.', ref: 'SEBI circular dt 22-Oct-2020: Recovery Expense Fund (now in NCS Master Circular)', s: 'V', d: 3 },
    { id: 'bo13', topic: 'NCD servicing', q: 'Payees for an NCD coupon are determined from:', o: ['Beneficiary position (BENPOS) from the depositories as on the record date', 'Beneficiary position (BENPOS) from the depositories as on the payment date', 'The allotment list from the EBP platform, updated for known transfers', 'Holders as per the RTA register on the deemed date of allotment'], a: 0, x: 'The RTA/BO downloads BENPOS as on record date; payment goes to those beneficial owners. Trades after record date settle ex-interest.', ref: 'Depository practice; SEBI NCS Master Circular (record date)', s: 'V', d: 1 },
    { id: 'bo14', topic: 'NCD servicing', q: 'Standard record date for interest/redemption on listed NCDs (SEBI) is:', o: ['15 days before the due date', '7 days before the due date', '30 days before the due date', '15 working days before the due date'], a: 0, x: 'SEBI standardised the record date for listed debt at 15 days prior to the due date. Check the term sheet for legacy ISINs.', ref: 'SEBI NCS Master Circular — standardisation of record date [REQUIRES LIVE VERIFICATION of circular no./date]', s: 'LV', d: 2 },
    // ---------- Tax & stamp ----------
    { id: 'bo15', topic: 'Tax', q: 'From 1-Apr-2023, interest on listed dematerialised debentures paid to residents:', o: ['Subject to TDS — Finance Act 2023 withdrew the exemption', 'Exempt from TDS when held in demat and listed', 'Subject to TDS only for individual and HUF investors', 'Subject to TDS only when annual interest exceeds ₹50 lakh'], a: 0, x: 'Finance Act 2023 withdrew the TDS exemption on listed demat debentures. BO must apply TDS (net of valid lower/nil certificates and exempt categories) on coupon runs. Note: the Income-tax Act, 2025 applies from 1-Apr-2026 — map section references.', ref: 'Finance Act 2023 (amendment to s.193, IT Act 1961); IT Act 2025 section mapping [verify]', s: 'V', d: 2 },
    { id: 'bo16', topic: 'Tax', q: 'TDS deducted on NCD coupons paid on 15-Jan (company deductor) must be deposited by:', o: ['7-Feb', '15-Feb', '31-Jan', '10-Feb'], a: 0, x: 'TDS is deposited by the 7th of the following month (for March deductions: 30-April).', ref: 'IT Rules 1962, Rule 30 — carry-over under IT Act 2025 regime [REQUIRES LIVE VERIFICATION]', s: 'LV', d: 1 },
    { id: 'bo17', topic: 'Tax', q: 'Stamp duty on issue of debentures (since 1-Jul-2020) is:', o: ['0.005% of consideration, collected via the depository/exchange mechanism', '0.0001% of consideration, collected via the depository/exchange mechanism', '0.005% of consideration, paid by the issuer to the state of registered office', '0.1% of consideration, collected via the debenture trustee'], a: 0, x: 'Issue of debentures: 0.005%; transfer: 0.0001%. Collected centrally through stock exchanges/clearing corporations/depositories under the amended Indian Stamp Act.', ref: 'Indian Stamp Act, 1899 as amended by Finance Act 2019; effective 01-Jul-2020', s: 'V', d: 2 },
    // ---------- ECB / FEMA ops ----------
    { id: 'bo18', topic: 'ECB ops', q: `${F} has an outstanding ECB. The ECB-2 return is filed:`, o: ['Monthly, via the AD bank, within 7 days of month-end', 'Monthly, via the AD bank, within 15 days of month-end', 'Quarterly, via the AD bank, within 30 days of quarter-end', 'Monthly, directly on RBI FIRMS, within 7 days of month-end'], a: 0, x: 'ECB-2 is a monthly return on actual transactions, filed via the AD bank within 7 days of month-end. Delays attract Late Submission Fee.', ref: 'RBI Master Direction – ECB, Trade Credits and Structured Obligations (26-Mar-2019, as updated) [REQUIRES LIVE VERIFICATION vs any revised ECB directions]', s: 'LV', d: 2 },
    { id: 'bo19', topic: 'ECB ops', q: 'Before the first drawdown of a new ECB, BO must ensure:', o: ['LRN obtained by submitting Form ECB through the AD bank', 'ECB-2 filed for the month of drawdown through the AD bank', 'Form ECB filed; LRN can follow within 30 days of drawdown', 'Board approval and FIRMS registration; no LRN for NBFCs'], a: 0, x: 'No drawdown before LRN allotment. Form ECB goes through the AD bank to RBI; changes to terms later need Form ECB revisions.', ref: 'RBI Master Direction – ECB (reporting: Form ECB / LRN)', s: 'V', d: 1 },
    // ---------- Accounting ----------
    { id: 'bo20', topic: 'Ind AS', q: 'Arranger fees and stamp duty on a ₹300 Cr 3-year NCD issue are accounted:', o: ['Included in the EIR and amortised over the NCD life', 'Expensed in P&L on the issue date as finance cost', 'Amortised straight-line over the NCD life as prepaid expense', 'Adjusted against securities premium on issue'], a: 0, x: 'Transaction costs directly attributable to a financial liability at amortised cost reduce its initial carrying amount and are amortised via the effective interest rate.', ref: 'Ind AS 109 para 5.1.1; Appendix A (effective interest method)', s: 'V', d: 2 },
    { id: 'bo21', topic: 'Ind AS', q: 'An IRS executed on 1-Jul to hedge a floating-rate term loan was documented as a hedge on 15-Aug. Hedge accounting can apply:', o: ['Prospectively from 15-Aug only — documentation is required at inception', 'Retrospectively from 1-Jul, if documented within the same quarter', 'From 1-Jul, provided the hedge proves effective at quarter-end', 'From the next financial year, once auditors review the file'], a: 0, x: 'Ind AS 109 requires formal designation and documentation at inception of the hedging relationship. Late paperwork = P&L volatility until designation. BO/MO must document on trade date.', ref: 'Ind AS 109 para 6.4.1(b)', s: 'V', d: 3 },
    { id: 'bo22', topic: 'Ind AS', q: `${F} securitises a pool via PTCs, providing a 12% first-loss cash collateral. Under Ind AS 109 the pool is most likely:`, o: ['Not derecognised — substantially all risks and rewards retained', 'Fully derecognised — legal true sale to the SPV', 'Derecognised; cash collateral shown as a contingent liability', 'Partly derecognised — 88% off, 12% retained on balance sheet'], a: 0, x: 'A first-loss enhancement sized well above expected loss typically means the originator retains substantially all risks and rewards → no derecognition; proceeds recorded as a borrowing.', ref: 'Ind AS 109 paras 3.2.6–3.2.7', s: 'V', d: 3 },
    { id: 'bo23', topic: 'Ind AS', q: 'A 91-day CP issued at a discount spans a month-end. At month-end, BO books:', o: ['Discount accreted for days elapsed using the EIR', 'Discount accreted straight-line only at quarter-end', 'Full discount recognised on the issue date', 'Nil — discount recognised in full at maturity'], a: 0, x: 'CP is a liability at amortised cost; the discount is the interest cost, recognised over time using EIR.', ref: 'Ind AS 109 — amortised cost / EIR', s: 'V', d: 1 },
    // ---------- Market infrastructure ----------
    { id: 'bo24', topic: 'Settlement', q: 'OTC secondary-market G-sec trades are settled:', o: ['Via CCIL as CCP, DvP-III (net funds, net securities), standard T+1', 'Via CCIL as CCP, DvP-I (gross), standard T+2', 'Via CCIL as CCP, DvP-III, standard T+0 for all trades', 'Bilaterally on RBI\'s e-Kuber, DvP-II, standard T+1'], a: 0, x: 'G-sec outright trades settle via CCIL (novation) on DvP-III. T+1 is standard; T+0 is permitted for certain trades.', ref: 'RBI/CCIL G-sec settlement framework', s: 'V', d: 2 },
    { id: 'bo25', topic: 'Settlement', q: 'OTC trades in corporate bonds are settled:', o: ['Via exchange clearing corporations on DvP-I (trade-by-trade gross)', 'Via CCIL on DvP-III (multilateral net)', 'Via exchange clearing corporations on DvP-III (multilateral net)', 'Bilaterally via RTGS against off-market depository transfer'], a: 0, x: 'SEBI requires OTC corporate bond trades to be reported and settled through clearing corporations (NCL/ICCL) on DvP-I — trade-by-trade gross for funds and securities.', ref: 'SEBI circulars on clearing & settlement of OTC corporate bond trades', s: 'V', d: 2 },
    { id: 'bo26', topic: 'Settlement', q: `${F} lends ₹200 Cr overnight in TREPS. Its counterparty exposure is on:`, o: ['CCIL, as central counterparty after novation', 'The borrowing bank, collateralised by its G-secs', 'The tri-party agent, as collateral manager', 'The borrowing bank, guaranteed by CCIL\'s default fund'], a: 0, x: 'TREPS is anonymous and centrally cleared — CCIL novates and guarantees settlement. Exposure is to the CCP, backed by collateral and default fund.', ref: 'CCIL TREPS segment rules', s: 'V', d: 1 },
    { id: 'bo27', topic: 'Settlement', q: `Eligible collateral when ${F} borrows in TREPS:`, o: ['G-secs, SDLs and T-bills in the CCIL collateral pool', 'G-secs, T-bills and AAA PSU bonds in the collateral pool', 'G-secs and T-bills only; SDLs are not eligible', 'Any SLR-eligible security, including CDs'], a: 0, x: 'TREPS is a tri-party repo on sovereign collateral. An NBFC must hold G-secs/T-bills (e.g. its LCR HQLA) to borrow in TREPS.', ref: 'CCIL TREPS segment rules', s: 'V', d: 2 },
    { id: 'bo28', topic: 'Liquidity', q: `Monday 11:00: ${F} needs ₹150 Cr for a CP redemption at 15:00 today. Which source CANNOT fund it?`, o: ['A liquid fund redemption placed Monday 09:30', 'Same-day drawdown of a committed WCDL', 'TREPS borrowing against T-bills held', 'Current account balance after morning collections'], a: 0, x: 'Liquid/overnight fund redemptions pay out T+1 — useless for a same-day need. Same-day sources: cash, committed lines with same-day drawdown, TREPS against collateral.', ref: 'SEBI MF redemption timelines (liquid funds T+1 practice)', s: 'V', d: 2 },
    { id: 'bo29', topic: 'Payments', q: 'A "fat-finger" RTGS of ₹250 Cr instead of ₹25 Cr is credited to a counterparty. RTGS payments are:', o: ['Final once settled — recovery needs beneficiary consent or legal process', 'Recallable by the remitting bank within the same RTGS business day', 'Auto-returned by the beneficiary bank if the amount exceeds the invoice', 'Reversible by RBI on a joint request from both banks'], a: 0, x: 'RTGS settlement is final. Immediate steps: alert your bank to contact the beneficiary bank, request a hold/return, escalate legally, and fund any resulting shortfall.', ref: 'RTGS System Regulations (finality of settlement); Payment and Settlement Systems Act, 2007 s.23', s: 'V', d: 2 },
    { id: 'bo30', topic: 'Payments', q: 'Before an RTGS/NEFT, the bank portal shows the beneficiary account holder\'s name. This facility:', o: ['Mandated by RBI for RTGS and NEFT (beneficiary name look-up) by 1-Apr-2025', 'Mandated by RBI only for NEFT; RTGS is bank discretion', 'A voluntary IBA initiative with no RBI mandate', 'Mandated by NPCI for IMPS and extended to RTGS by banks'], a: 0, x: 'RBI required banks to offer beneficiary name look-up for RTGS and NEFT (similar to UPI/IMPS) to reduce misdirected and fraudulent credits.', ref: 'RBI circular dt 30-Dec-2024 (beneficiary account name look-up) [REQUIRES LIVE VERIFICATION]', s: 'LV', d: 2 },
    { id: 'bo31', topic: 'Payments', q: 'CTS Positive Pay (from 1-Jan-2021) applies to cheques of:', o: ['₹50,000 and above; banks may make it mandatory for ₹5 lakh and above', '₹5 lakh and above; mandatory for ₹50 lakh and above', '₹50,000 and above; mandatory for all corporate accounts', '₹1 lakh and above; mandatory for ₹10 lakh and above'], a: 0, x: 'Positive Pay requires the drawer to re-confirm key cheque details. Treasury cheques (rare, but used for some refunds) should always be on Positive Pay.', ref: 'RBI circular dt 25-Sep-2020: Positive Pay System for CTS', s: 'V', d: 2 },
    { id: 'bo32', topic: 'Derivatives ops', q: 'The floating leg of an INR OIS on overnight MIBOR accrues on:', o: ['Daily compounding of FBIL overnight MIBOR, Act/365', 'Simple average of FBIL overnight MIBOR, Act/365', 'Daily compounding of FBIL overnight MIBOR, Act/360', 'Daily compounding of the RBI policy repo rate, Act/365'], a: 0, x: 'INR OIS: compounded overnight rate vs fixed, Act/365, net settled. BO validates the compounded rate independently of the counterparty bank. Watch for benchmark transition.', ref: 'FIMMDA/FBIL conventions for INR OIS [benchmark transition: REQUIRES LIVE VERIFICATION]', s: 'V', d: 2 },
    // ---------- Controls & conduct ----------
    { id: 'bo33', topic: 'Controls', q: 'Two days before a CP maturity, an email from an MF investor\'s "treasury" asks to change the redemption bank account. What do you do?', o: ['Hold; call back on an independently sourced number and require signed authorised-signatory request', 'Update after replying to the same email thread for written confirmation', 'Update, since the email domain matches the investor\'s registered domain', 'Ask the dealer to confirm the change with the fund manager by phone'], a: 0, x: 'SSI/bank-detail changes near a payment date are the textbook business-email-compromise pattern. Call-back verification + authorised signatories + maker-checker in static data. Dealers must not validate SSIs.', ref: 'Control best practice (BEC / SSI change protocol)', s: 'C', d: 1 },
    { id: 'bo34', topic: 'Controls', q: 'Who should release a ₹150 Cr payment after the BO maker inputs it on the bank portal?', o: ['An authorised BO checker independent of the maker and the dealing desk', 'The dealer who executed the trade, as second authoriser', 'The maker, using the checker\'s token with documented approval', 'An authorised Treasury checker who also manages the dealing limits'], a: 0, x: 'Segregation of duties: front office executes; BO inputs and authorises with separate individuals; tokens are personal and never shared.', ref: 'Control best practice; RBI guidance on internal controls', s: 'C', d: 1 },
    { id: 'bo35', topic: 'Controls', q: 'At 16:50 a dealer asks BO to "just settle" an FX forward with a bank — the trade is in the system but no counterparty confirmation has been received. You:', o: ['Escalate as unconfirmed, chase the bank\'s ops for a matched confirmation, log the exception', 'Settle on the dealer\'s chat transcript and log the confirmation as pending', 'Mark confirmed using the bank dealer\'s email forwarded by our dealer', 'Cancel the trade and ask the dealer to rebook tomorrow'], a: 0, x: 'Confirmations must be exchanged ops-to-ops, independent of dealers. Unconfirmed trades are tracked and aged on an exceptions report reviewed by MO.', ref: 'Control best practice (confirmation independence)', s: 'C', d: 2 },
    { id: 'bo36', topic: 'Controls', q: 'A ₹4.2 Cr credit sits unidentified in the collection account for 3 days. Best treatment:', o: ['Park in suspense with ageing, trace via UTR with the remitting bank, escalate per policy', 'Appropriate to the oldest overdue loan pending identification', 'Credit to other income after 3 days and reverse if claimed', 'Return to the remitter immediately via the same rail'], a: 0, x: 'Unidentified credits go to suspense with ageing and investigation. Arbitrary appropriation misstates the loan book and customer balances.', ref: 'Reconciliation best practice', s: 'C', d: 1 },
    { id: 'bo37', topic: 'Liquidity', q: 'Shortfall day: ₹300 Cr available. Due today: CP redemption ₹250 Cr, discretionary disbursement batch ₹80 Cr, vendor payments ₹10 Cr. Release order?', o: ['CP redemption in full; defer discretionary disbursements; vendors as cash permits', 'Pro-rata across all obligations to treat counterparties equally', 'CP redemption ₹220 Cr now, balance after disbursements clear', 'Vendors (MSME timelines) first, then CP, then disbursements'], a: 0, x: 'A market-instrument default triggers rating action, cross-default and a run on rollover. Disbursements are discretionary and can be paced. Escalate to the Treasurer/CFO immediately.', ref: 'Contingency Funding Plan practice; RBI Liquidity Risk Management Framework for NBFCs (04-Nov-2019)', s: 'C', d: 2 },
    { id: 'bo38', topic: 'Controls', q: 'Counterparty SSI static data in the treasury system should be maintained by:', o: ['Back Office/Ops with maker-checker, independent of dealers', 'Dealers, as they hold the counterparty relationship', 'IT administrators, with Back Office approval', 'Back Office, with the dealer as checker for speed'], a: 0, x: 'Whoever controls the SSI controls where money goes. Static data sits with independent Ops, with maker-checker and an audit trail.', ref: 'Control best practice', s: 'C', d: 1 },
    { id: 'bo39', topic: 'Derivatives ops', q: 'For an IRS with a bank, the best evidence of terms for settlement is:', o: ['A confirmation matched between BO and the bank\'s operations', 'The recorded dealer voice log for the trade', 'The dealing chat transcript between both dealers', 'The bank dealer\'s email confirming terms to our dealer'], a: 0, x: 'Dealer-to-dealer records support disputes but are not the settlement record. Ops-to-ops matching is the control.', ref: 'Control best practice; ISDA confirmation practice', s: 'C', d: 1 },
    { id: 'bo40', topic: 'Settlement', q: 'For a G-sec sale settling T+1 via CCIL, the settlement consideration equals:', o: ['Clean price × FV/100 + accrued (30/360) from last coupon to settlement date', 'Clean price × FV/100 + accrued (Act/365) from last coupon to settlement date', 'Clean price × FV/100 + accrued (30/360) from last coupon to trade date', 'Clean price × FV/100 only; accrued is settled on the next coupon date'], a: 0, x: 'G-secs trade clean; settlement is dirty = clean + accrued. Indian G-sec accrual uses 30/360 with semi-annual coupons.', ref: 'FIMMDA/RBI G-sec market conventions', s: 'V', d: 2 },
    { id: 'bo41', topic: 'NCD servicing', q: 'A coupon run is due Monday; the RTA\'s payee file shows 3 investors with failed bank validation. Best action:', o: ['Pay validated holders on time; hold the 3 in a separate payable and pay once mandates are fixed', 'Delay the entire run by one day until all mandates are validated', 'Pay the 3 by demand draft to the depository address without validation', 'Pay the 3 to the arranger\'s account to pass on'], a: 0, x: 'Never delay the whole run for exceptions. Unpaid amounts are held identifiably and tracked; the due date is met for all payable holders.', ref: 'NCD servicing practice (RTA / unpaid interest handling)', s: 'C', d: 2 },
    { id: 'bo42', topic: 'CP operations', q: 'Who acts as Issuing and Paying Agent (IPA) for a CP?', o: ['A scheduled bank', 'A SEBI-registered RTA', 'A SEBI-registered debenture trustee', 'A depository participant'], a: 0, x: 'The IPA is a scheduled bank. It verifies documents, handles issuance in demat form and redemption. BO must fund the IPA account before redemption.', ref: 'RBI CP & short-term NCD Directions, 2024', s: 'V', d: 1 }
  ];

  /* ---------------- generators ---------------- */
  const G = [];
  const opt4 = (r, correct, wrongs) => { // mcq from numeric/text values
    const o = r.shuffle([correct, ...wrongs]); return { o, a: o.indexOf(correct) };
  };
  // G1: CP discount
  G.push(function (r) {
    const fv = r.pick([25, 50, 75, 100, 150, 200, 250]), y = r.step(6.8, 8.2, 0.05), d = r.pick([30, 45, 60, 91, 120, 182, 273, 364]);
    const price = fv / (1 + (y / 100) * d / 365), disc = (fv - price) * 100; // ₹ lakh
    if (r() < 0.5) return { id: 'g-cp1', topic: 'CP maths', t: 'num', q: `${F} issues a ${d}-day CP, FV ${D.cr(fv, 0)}, at a discount yield of ${y.toFixed(2)}% (Act/365). Discount amount in ₹ lakh?`, a: D.round(disc, 2), tol: 0.02, unit: '₹ lakh', dp: 2, x: `Price = FV ÷ (1 + y × d/365) = ${fv} ÷ (1 + ${(y / 100).toFixed(4)} × ${d}/365) = ${D.fmt(price, 6)} Cr. Discount = ${D.fmt(fv - price, 6)} Cr = ₹${D.fmt(disc, 2)} lakh.`, ref: 'CP yield convention: discount yield on Act/365', s: 'G', d: 2 };
    const p100 = 100 / (1 + (y / 100) * d / 365);
    return { id: 'g-cp2', topic: 'CP maths', t: 'num', q: `${d}-day CP at ${y.toFixed(2)}% yield (Act/365). Issue price per ₹100 FV (4 dp)?`, a: D.round(p100, 4), tol: 0.0002, unit: 'per ₹100', dp: 4, x: `100 ÷ (1 + ${y.toFixed(2)}% × ${d}/365) = ${D.fmt(p100, 4)}.`, ref: 'CP yield convention: Act/365', s: 'G', d: 2 };
  });
  // G2: NCD broken period interest
  G.push(function (r) {
    const fv = r.pick([100, 150, 200, 250, 300, 500]), c = r.step(7.2, 9.2, 0.05);
    const yr = r.pick([2027, 2028, 2029]);
    const cpn = D.date(yr, r.pick([3, 6, 9]), r.pick([15, 30]));
    const allot = D.addDays(cpn, -r.int(40, 300));
    const days = D.days(allot, cpn);
    let leap = false; for (let t = allot; t < cpn; t = D.addDays(t, 1)) if (t.getUTCMonth() === 1 && t.getUTCDate() === 29) leap = true;
    const den = leap ? 366 : 365, intL = fv * 100 * (c / 100) * days / den;
    return { id: 'g-ncd1', topic: 'NCD maths', t: 'num', q: `NCD FV ${D.cr(fv, 0)}, coupon ${c.toFixed(2)}% annual. Deemed allotment ${D.dfmt(allot)}; first coupon ${D.dfmt(cpn)}. Act/Act (366 if 29-Feb falls in period); days = coupon date − allotment date. First (broken) coupon in ₹ lakh?`, a: D.round(intL, 2), tol: 0.02, unit: '₹ lakh', dp: 2, x: `Days = ${days}; ${leap ? '29-Feb falls in the period → 366' : 'no 29-Feb in period → 365'}. Interest = ${fv} Cr × ${c.toFixed(2)}% × ${days}/${den} = ₹${D.fmt(intL, 2)} lakh.`, ref: 'SEBI CIR/IMD/DF-1/122/2016 — Actual/Actual', s: 'G', d: 3 };
  });
  // G3: net coupon after TDS
  G.push(function (r) {
    const h = r.pick([5, 10, 15, 20, 25, 40, 50]), c = r.step(7.5, 9.5, 0.05);
    const gross = h * 100 * c / 100, net = gross * 0.9;
    const w = [D.round(gross, 2), D.round(gross * 0.95, 2), D.round(gross * 0.8, 2)];
    const m = opt4(r, D.round(net, 2), w);
    return { id: 'g-tds', topic: 'Tax', q: `A resident company (valid PAN, no lower-deduction certificate) holds ${D.cr(h, 0)} of ${F}'s listed ${c.toFixed(2)}% annual-coupon NCD. Full-year coupon credited to it, net of 10% TDS (₹ lakh):`, o: m.o.map((v) => '₹' + D.fmt(v, 2) + ' lakh'), a: m.a, x: `Gross = ${h} Cr × ${c.toFixed(2)}% = ₹${D.fmt(gross, 2)} lakh; TDS 10% = ₹${D.fmt(gross * 0.1, 2)} lakh; net = ₹${D.fmt(net, 2)} lakh. (Rate assumes the 10% resident rate — verify under the IT Act 2025.)`, ref: 'TDS on interest on securities — 10% resident rate [REQUIRES LIVE VERIFICATION under IT Act 2025]', s: 'LV', d: 1 };
  });
  // G4: bank reconciliation
  G.push(function (r) {
    const B = r.step(120, 480, 0.01), Dt = r.step(5, 40, 0.01), U = r.step(5, 60, 0.01), C = r.step(0.01, 0.4, 0.01), I = r.step(0.05, 1.5, 0.01);
    const bank = B - C + I - Dt + U;
    return { id: 'g-brs', topic: 'Reconciliation', t: 'num', q: `Book (ledger) balance: ${D.cr(B)}. Deposits recorded in books but not yet credited by bank: ${D.cr(Dt)}. Payments issued but not yet debited by bank: ${D.cr(U)}. Bank charges not yet booked: ${D.cr(C)}. Interest credited by bank not yet booked: ${D.cr(I)}. What does the bank statement show (₹ Cr)?`, a: D.round(bank, 2), tol: 0.011, unit: '₹ Cr', dp: 2, x: `Adjusted book = ${D.fmt(B)} − ${D.fmt(C)} + ${D.fmt(I)} = ${D.fmt(B - C + I)}. Bank = adjusted book − deposits in transit + unpresented payments = ${D.fmt(B - C + I)} − ${D.fmt(Dt)} + ${D.fmt(U)} = ${D.fmt(bank)} Cr.`, ref: 'Bank reconciliation method', s: 'G', d: 2 };
  });
  // G5: OIS net settlement
  G.push(function (r) {
    const N = r.pick([50, 100, 200, 250, 500]), Fx = D.round(r.step(5.4, 6.4, 0.01), 2), d = r.pick([91, 182, 184]);
    let dl = D.round(r.step(-0.6, 0.6, 0.01), 2); if (Math.abs(dl) < 0.05) dl = 0.13;
    const R = D.round(Fx + dl, 2);
    const amt = N * (Fx - R) * d / 365, a360 = N * (Fx - R) * d / 360; // lakh
    const pays = amt > 0, A = Math.abs(amt), A3 = Math.abs(a360);
    const L = (p, v) => `${F} ${p ? 'pays' : 'receives'} ₹${D.fmt(v, 2)} lakh`;
    const m = opt4(r, L(pays, A), [L(!pays, A), L(pays, A3), L(!pays, A3)]);
    return { id: 'g-ois', topic: 'Derivatives ops', q: `${F} pays fixed ${Fx.toFixed(2)}% / receives compounded overnight MIBOR on an OIS, notional ${D.cr(N, 0)}. For a ${d}-day period, realised compounded rate = ${R.toFixed(2)}%. Net settlement (Act/365)?`, o: m.o, a: m.a, x: `Net = N × (Fixed − Float) × d/365 = ${N} Cr × (${Fx.toFixed(2)} − ${R.toFixed(2)})% × ${d}/365 = ₹${D.fmt(amt, 2)} lakh. ${pays ? 'Fixed > float → fixed payer pays.' : 'Float > fixed → fixed payer receives.'}`, ref: 'INR OIS convention (Act/365, net settled)', s: 'G', d: 3 };
  });
  // G6: G-sec accrued interest 30/360
  G.push(function (r) {
    const c = r.step(6.1, 7.6, 0.01), m1 = r.pick([1, 2, 3, 4, 5, 6]), d1 = r.int(1, 28), y = 2026 + r.int(0, 1);
    const last = { y, m: m1, d: d1 };
    let m2 = m1 + r.int(0, 5), d2 = r.int(1, 28); if (m2 === m1 && d2 <= d1) d2 = Math.min(28, d1 + r.int(3, 20));
    if (m2 === m1 && d2 <= d1) { m2 = m1 + 1; }
    const days = (m2 - m1) * 30 + (d2 - d1);
    const ai = c * days / 360;
    const sd = D.date(y, m2, d2);
    return { id: 'g-gsec', topic: 'Settlement maths', t: 'num', q: `G-sec, coupon ${c.toFixed(2)}% (semi-annual). Last coupon date ${D.dfmt(D.date(y, m1, d1), false)}; settlement date ${D.dfmt(sd, false)}. Accrued interest per ₹100 FV on 30/360 (4 dp)?`, a: D.round(ai, 4), tol: 0.0002, unit: 'per ₹100', dp: 4, x: `30/360 days = (${m2}−${m1})×30 + (${d2}−${d1}) = ${days}. Accrued = ${c.toFixed(2)} × ${days}/360 = ${D.fmt(ai, 4)}.`, ref: 'G-sec convention: 30/360, semi-annual coupon', s: 'G', d: 2 };
  });
  // G7: default interest
  G.push(function (r) {
    const fv = r.pick([50, 100, 200, 300]), dd = r.int(1, 12);
    const x = fv * 100 * 0.02 * dd / 365;
    return { id: 'g-dflt', topic: 'NCD maths', t: 'num', q: `An NCD redemption of ${D.cr(fv, 0)} is paid ${dd} day(s) late. Additional default interest at 2% p.a. over coupon (Act/365) — the additional amount only, in ₹ lakh?`, a: D.round(x, 2), tol: 0.02, unit: '₹ lakh', dp: 2, x: `${fv} Cr × 2% × ${dd}/365 = ₹${D.fmt(x, 2)} lakh — on top of coupon for the delay period, plus rating and disclosure consequences.`, ref: 'SEBI NCS Master Circular — default interest', s: 'G', d: 2 };
  });
  // G8: TREPS interest
  G.push(function (r) {
    const A = r.pick([50, 100, 150, 200, 300, 400, 500]), rt = r.step(5.1, 5.9, 0.01), d = r.pick([1, 1, 3]);
    const x = A * rt * d / 365;
    return { id: 'g-treps', topic: 'Money markets', t: 'num', q: `${F} lends ${D.cr(A, 0)} in TREPS at ${rt.toFixed(2)}% for ${d === 3 ? '3 days (Friday → Monday)' : '1 day (overnight)'}. Interest receivable in ₹ lakh (Act/365)?`, a: D.round(x, 2), tol: 0.01, unit: '₹ lakh', dp: 2, x: `${A} Cr × ${rt.toFixed(2)}% × ${d}/365 = ₹${D.fmt(x, 2)} lakh.`, ref: 'TREPS convention: Act/365', s: 'G', d: 1 };
  });

  D.content.bo = { name: 'Back Office', S, G };
})();
